plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

javafx {
    version = "21.0.2"
    modules = ['javafx.controls', 'javafx.graphics']
}

application {
    mainClass = 'org.firstinspires.ftc.teamcode.odysseygui.Main'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':odyssey-core')
}